In [1]:
import os
import matplotlib.pyplot as plt
import tensorflow as tf

In [2]:
def parse_label(path):
    raw = open(path,encoding='utf-8').read()
    classnames =[]
    for cls in raw.split('\n'):
        if cls == '':
            continue
        classnames.append(cls)
    return classnames
train_dir = 'data/train/'
class_names = parse_label(train_dir+'classes_label.txt')
train_file_dirs = [train_dir+classname for classname in class_names] 

In [3]:
for i,file_dir in enumerate(train_file_dirs):
    for filename in os.listdir(file_dir):
        filename = file_dir+'/'+filename
#         print(filename)
        image_raw_data = tf.io.read_file(filename)
        image_decoded = tf.image.decode_jpeg(image_raw_data,3)
#         if filename.endswith('jpg') or filename.endswith('jpeg'):
#            continue
#         elif filename.endswith('png'):
#             image_decoded = tf.image.decode_png(image_raw_data)  # 解码PNG图片
#         elif filename.endswith('gif'):
#             image_decoded = tf.image.decode_png(image_raw_data)  # 解码GIF图片
        encoded_image = tf.io.encode_jpeg(image_decoded)
        tf.io.write_file(filename.split('.')[0]+'.jpg',encoded_image)

In [40]:
def _decode_and_resize(filename, label):
    image_string = tf.io.read_file(filename)  # 读取原始文件
    image_decoded = tf.io.decode_jpeg(image_string,channels=3)  # 解码JPEG图片
    image_resized = tf.image.resize(image_decoded, [224, 224]) / 255.0
    return image_resized, label

def load_data(dirs):
    images_name = []
    labels = []
    for i,file_dir in enumerate(dirs):
        filename = tf.constant([file_dir + '/' + filename for filename in os.listdir(file_dir)])
        print(filename)
        images_name = tf.concat([images_name,filename],axis=-1)
        labels = tf.concat([labels,tf.constant(i,shape=filename.shape[0])],axis=-1)
    print("total:%d" %  images_name.shape[0])
    train_dataset = tf.data.Dataset.from_tensor_slices((images_name, labels))
    train_dataset = train_dataset.map(
        map_func=_decode_and_resize,
        num_parallel_calls=tf.data.experimental.AUTOTUNE)
    return train_dataset

In [43]:
train_dataset = load_data([train_dir+'一次性筷子'])
train_dataset = train_dataset.batch(1)
for bn,(images,labels) in enumerate(train_dataset):
    print(bn)
    continue

tf.Tensor(
[b'data/train/\xe4\xb8\x80\xe6\xac\xa1\xe6\x80\xa7\xe7\xad\xb7\xe5\xad\x90/1.jpg'
 b'data/train/\xe4\xb8\x80\xe6\xac\xa1\xe6\x80\xa7\xe7\xad\xb7\xe5\xad\x90/10.jpg'
 b'data/train/\xe4\xb8\x80\xe6\xac\xa1\xe6\x80\xa7\xe7\xad\xb7\xe5\xad\x90/100.jpg'
 b'data/train/\xe4\xb8\x80\xe6\xac\xa1\xe6\x80\xa7\xe7\xad\xb7\xe5\xad\x90/101.jpg'
 b'data/train/\xe4\xb8\x80\xe6\xac\xa1\xe6\x80\xa7\xe7\xad\xb7\xe5\xad\x90/102.jpg'
 b'data/train/\xe4\xb8\x80\xe6\xac\xa1\xe6\x80\xa7\xe7\xad\xb7\xe5\xad\x90/103.jpg'
 b'data/train/\xe4\xb8\x80\xe6\xac\xa1\xe6\x80\xa7\xe7\xad\xb7\xe5\xad\x90/105.jpg'
 b'data/train/\xe4\xb8\x80\xe6\xac\xa1\xe6\x80\xa7\xe7\xad\xb7\xe5\xad\x90/107.png'
 b'data/train/\xe4\xb8\x80\xe6\xac\xa1\xe6\x80\xa7\xe7\xad\xb7\xe5\xad\x90/108.jpg'
 b'data/train/\xe4\xb8\x80\xe6\xac\xa1\xe6\x80\xa7\xe7\xad\xb7\xe5\xad\x90/109.jpg'
 b'data/train/\xe4\xb8\x80\xe6\xac\xa1\xe6\x80\xa7\xe7\xad\xb7\xe5\xad\x90/11.jpg'
 b'data/train/\xe4\xb8\x80\xe6\xac\xa1\xe6\x80\xa7\xe7\xad\xb7\xe5\xa

235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442


In [44]:
for train_file_dir in train_file_dirs:
    print(train_file_dir)
    train_dataset = load_data([train_file_dir])
    train_dataset = train_dataset.batch(1)
    for bn,(images,labels) in enumerate(train_dataset):
#         print(bn)
        continue

data/train/衣服
tf.Tensor(
[b'data/train/\xe8\xa1\xa3\xe6\x9c\x8d/clothes1.jpg'
 b'data/train/\xe8\xa1\xa3\xe6\x9c\x8d/clothes10.jpg'
 b'data/train/\xe8\xa1\xa3\xe6\x9c\x8d/clothes100.jpg' ...
 b'data/train/\xe8\xa1\xa3\xe6\x9c\x8d/clothes997.jpg'
 b'data/train/\xe8\xa1\xa3\xe6\x9c\x8d/clothes998.jpg'
 b'data/train/\xe8\xa1\xa3\xe6\x9c\x8d/clothes999.jpg'], shape=(2152,), dtype=string)
total:2152
data/train/玻璃
tf.Tensor(
[b'data/train/\xe7\x8e\xbb\xe7\x92\x83/green-glass1.jpg'
 b'data/train/\xe7\x8e\xbb\xe7\x92\x83/green-glass10.jpg'
 b'data/train/\xe7\x8e\xbb\xe7\x92\x83/green-glass100.jpg' ...
 b'data/train/\xe7\x8e\xbb\xe7\x92\x83/white-glass97.jpg'
 b'data/train/\xe7\x8e\xbb\xe7\x92\x83/white-glass98.jpg'
 b'data/train/\xe7\x8e\xbb\xe7\x92\x83/white-glass99.jpg'], shape=(1404,), dtype=string)
total:1404
data/train/口服液瓶
tf.Tensor(
[b'data/train/\xe5\x8f\xa3\xe6\x9c\x8d\xe6\xb6\xb2\xe7\x93\xb6/1.jpg'
 b'data/train/\xe5\x8f\xa3\xe6\x9c\x8d\xe6\xb6\xb2\xe7\x93\xb6/10.jpg'
 b'data/train/\

data/train/鞋
tf.Tensor(
[b'data/train/\xe9\x9e\x8b/shoes1.jpg'
 b'data/train/\xe9\x9e\x8b/shoes10.jpg'
 b'data/train/\xe9\x9e\x8b/shoes100.jpg' ...
 b'data/train/\xe9\x9e\x8b/shoes997.jpg'
 b'data/train/\xe9\x9e\x8b/shoes998.jpg'
 b'data/train/\xe9\x9e\x8b/shoes999.jpg'], shape=(1977,), dtype=string)
total:1977
data/train/塑料
tf.Tensor(
[b'data/train/\xe5\xa1\x91\xe6\x96\x99/plastic1.jpg'
 b'data/train/\xe5\xa1\x91\xe6\x96\x99/plastic10.jpg'
 b'data/train/\xe5\xa1\x91\xe6\x96\x99/plastic100.jpg'
 b'data/train/\xe5\xa1\x91\xe6\x96\x99/plastic101.jpg'
 b'data/train/\xe5\xa1\x91\xe6\x96\x99/plastic102.jpg'
 b'data/train/\xe5\xa1\x91\xe6\x96\x99/plastic103.jpg'
 b'data/train/\xe5\xa1\x91\xe6\x96\x99/plastic104.jpg'
 b'data/train/\xe5\xa1\x91\xe6\x96\x99/plastic105.jpg'
 b'data/train/\xe5\xa1\x91\xe6\x96\x99/plastic106.jpg'
 b'data/train/\xe5\xa1\x91\xe6\x96\x99/plastic107.jpg'
 b'data/train/\xe5\xa1\x91\xe6\x96\x99/plastic108.jpg'
 b'data/train/\xe5\xa1\x91\xe6\x96\x99/plastic109.jpg'
 b'da

data/train/报纸
tf.Tensor(
[b'data/train/\xe6\x8a\xa5\xe7\xba\xb8/paper1.jpg'
 b'data/train/\xe6\x8a\xa5\xe7\xba\xb8/paper10.jpg'
 b'data/train/\xe6\x8a\xa5\xe7\xba\xb8/paper100.jpg' ...
 b'data/train/\xe6\x8a\xa5\xe7\xba\xb8/paper997.jpg'
 b'data/train/\xe6\x8a\xa5\xe7\xba\xb8/paper998.jpg'
 b'data/train/\xe6\x8a\xa5\xe7\xba\xb8/paper999.jpg'], shape=(1050,), dtype=string)
total:1050
data/train/易拉罐
tf.Tensor(
[b'data/train/\xe6\x98\x93\xe6\x8b\x89\xe7\xbd\x90/metal1.jpg'
 b'data/train/\xe6\x98\x93\xe6\x8b\x89\xe7\xbd\x90/metal10.jpg'
 b'data/train/\xe6\x98\x93\xe6\x8b\x89\xe7\xbd\x90/metal100.jpg'
 b'data/train/\xe6\x98\x93\xe6\x8b\x89\xe7\xbd\x90/metal101.jpg'
 b'data/train/\xe6\x98\x93\xe6\x8b\x89\xe7\xbd\x90/metal102.jpg'
 b'data/train/\xe6\x98\x93\xe6\x8b\x89\xe7\xbd\x90/metal103.jpg'
 b'data/train/\xe6\x98\x93\xe6\x8b\x89\xe7\xbd\x90/metal104.jpg'
 b'data/train/\xe6\x98\x93\xe6\x8b\x89\xe7\xbd\x90/metal105.jpg'
 b'data/train/\xe6\x98\x93\xe6\x8b\x89\xe7\xbd\x90/metal106.jpg'
 b'dat

data/train/纸箱
tf.Tensor(
[b'data/train/\xe7\xba\xb8\xe7\xae\xb1/cardboard1.jpg'
 b'data/train/\xe7\xba\xb8\xe7\xae\xb1/cardboard10.jpg'
 b'data/train/\xe7\xba\xb8\xe7\xae\xb1/cardboard100.jpg'
 b'data/train/\xe7\xba\xb8\xe7\xae\xb1/cardboard101.jpg'
 b'data/train/\xe7\xba\xb8\xe7\xae\xb1/cardboard102.jpg'
 b'data/train/\xe7\xba\xb8\xe7\xae\xb1/cardboard103.jpg'
 b'data/train/\xe7\xba\xb8\xe7\xae\xb1/cardboard104.jpg'
 b'data/train/\xe7\xba\xb8\xe7\xae\xb1/cardboard105.jpg'
 b'data/train/\xe7\xba\xb8\xe7\xae\xb1/cardboard106.jpg'
 b'data/train/\xe7\xba\xb8\xe7\xae\xb1/cardboard107.jpg'
 b'data/train/\xe7\xba\xb8\xe7\xae\xb1/cardboard108.jpg'
 b'data/train/\xe7\xba\xb8\xe7\xae\xb1/cardboard109.jpg'
 b'data/train/\xe7\xba\xb8\xe7\xae\xb1/cardboard11.jpg'
 b'data/train/\xe7\xba\xb8\xe7\xae\xb1/cardboard110.jpg'
 b'data/train/\xe7\xba\xb8\xe7\xae\xb1/cardboard111.jpg'
 b'data/train/\xe7\xba\xb8\xe7\xae\xb1/cardboard112.jpg'
 b'data/train/\xe7\xba\xb8\xe7\xae\xb1/cardboard113.jpg'
 b'data/tr

data/train/食品
tf.Tensor(
[b'data/train/\xe9\xa3\x9f\xe5\x93\x81/biological1.jpg'
 b'data/train/\xe9\xa3\x9f\xe5\x93\x81/biological10.jpg'
 b'data/train/\xe9\xa3\x9f\xe5\x93\x81/biological100.jpg'
 b'data/train/\xe9\xa3\x9f\xe5\x93\x81/biological101.jpg'
 b'data/train/\xe9\xa3\x9f\xe5\x93\x81/biological102.jpg'
 b'data/train/\xe9\xa3\x9f\xe5\x93\x81/biological103.jpg'
 b'data/train/\xe9\xa3\x9f\xe5\x93\x81/biological104.jpg'
 b'data/train/\xe9\xa3\x9f\xe5\x93\x81/biological105.jpg'
 b'data/train/\xe9\xa3\x9f\xe5\x93\x81/biological106.jpg'
 b'data/train/\xe9\xa3\x9f\xe5\x93\x81/biological107.jpg'
 b'data/train/\xe9\xa3\x9f\xe5\x93\x81/biological108.jpg'
 b'data/train/\xe9\xa3\x9f\xe5\x93\x81/biological109.jpg'
 b'data/train/\xe9\xa3\x9f\xe5\x93\x81/biological11.jpg'
 b'data/train/\xe9\xa3\x9f\xe5\x93\x81/biological110.jpg'
 b'data/train/\xe9\xa3\x9f\xe5\x93\x81/biological111.jpg'
 b'data/train/\xe9\xa3\x9f\xe5\x93\x81/biological112.jpg'
 b'data/train/\xe9\xa3\x9f\xe5\x93\x81/biological11

data/train/电池
tf.Tensor(
[b'data/train/\xe7\x94\xb5\xe6\xb1\xa0/battery1.jpg'
 b'data/train/\xe7\x94\xb5\xe6\xb1\xa0/battery10.jpg'
 b'data/train/\xe7\x94\xb5\xe6\xb1\xa0/battery100.jpg'
 b'data/train/\xe7\x94\xb5\xe6\xb1\xa0/battery101.jpg'
 b'data/train/\xe7\x94\xb5\xe6\xb1\xa0/battery102.jpg'
 b'data/train/\xe7\x94\xb5\xe6\xb1\xa0/battery103.jpg'
 b'data/train/\xe7\x94\xb5\xe6\xb1\xa0/battery104.jpg'
 b'data/train/\xe7\x94\xb5\xe6\xb1\xa0/battery105.jpg'
 b'data/train/\xe7\x94\xb5\xe6\xb1\xa0/battery106.jpg'
 b'data/train/\xe7\x94\xb5\xe6\xb1\xa0/battery107.jpg'
 b'data/train/\xe7\x94\xb5\xe6\xb1\xa0/battery108.jpg'
 b'data/train/\xe7\x94\xb5\xe6\xb1\xa0/battery109.jpg'
 b'data/train/\xe7\x94\xb5\xe6\xb1\xa0/battery11.jpg'
 b'data/train/\xe7\x94\xb5\xe6\xb1\xa0/battery110.jpg'
 b'data/train/\xe7\x94\xb5\xe6\xb1\xa0/battery111.jpg'
 b'data/train/\xe7\x94\xb5\xe6\xb1\xa0/battery112.jpg'
 b'data/train/\xe7\x94\xb5\xe6\xb1\xa0/battery113.jpg'
 b'data/train/\xe7\x94\xb5\xe6\xb1\xa0/batte

data/train/打火机
tf.Tensor(
[b'data/train/\xe6\x89\x93\xe7\x81\xab\xe6\x9c\xba/1.jpg'
 b'data/train/\xe6\x89\x93\xe7\x81\xab\xe6\x9c\xba/10.jpg'
 b'data/train/\xe6\x89\x93\xe7\x81\xab\xe6\x9c\xba/101.jpg'
 b'data/train/\xe6\x89\x93\xe7\x81\xab\xe6\x9c\xba/102.jpg'
 b'data/train/\xe6\x89\x93\xe7\x81\xab\xe6\x9c\xba/103.jpg'
 b'data/train/\xe6\x89\x93\xe7\x81\xab\xe6\x9c\xba/104.jpeg'
 b'data/train/\xe6\x89\x93\xe7\x81\xab\xe6\x9c\xba/105.png'
 b'data/train/\xe6\x89\x93\xe7\x81\xab\xe6\x9c\xba/107.jpg'
 b'data/train/\xe6\x89\x93\xe7\x81\xab\xe6\x9c\xba/109.jpeg'
 b'data/train/\xe6\x89\x93\xe7\x81\xab\xe6\x9c\xba/11.jpg'
 b'data/train/\xe6\x89\x93\xe7\x81\xab\xe6\x9c\xba/111.jpeg'
 b'data/train/\xe6\x89\x93\xe7\x81\xab\xe6\x9c\xba/112.jpg'
 b'data/train/\xe6\x89\x93\xe7\x81\xab\xe6\x9c\xba/115.jpeg'
 b'data/train/\xe6\x89\x93\xe7\x81\xab\xe6\x9c\xba/117.png'
 b'data/train/\xe6\x89\x93\xe7\x81\xab\xe6\x9c\xba/118.jpeg'
 b'data/train/\xe6\x89\x93\xe7\x81\xab\xe6\x9c\xba/12.jpg'
 b'data/train/

data/train/废弃灯泡
tf.Tensor(
[b'data/train/\xe5\xba\x9f\xe5\xbc\x83\xe7\x81\xaf\xe6\xb3\xa1/1.jpeg'
 b'data/train/\xe5\xba\x9f\xe5\xbc\x83\xe7\x81\xaf\xe6\xb3\xa1/10.jpg'
 b'data/train/\xe5\xba\x9f\xe5\xbc\x83\xe7\x81\xaf\xe6\xb3\xa1/100.jpg'
 b'data/train/\xe5\xba\x9f\xe5\xbc\x83\xe7\x81\xaf\xe6\xb3\xa1/101.jpeg'
 b'data/train/\xe5\xba\x9f\xe5\xbc\x83\xe7\x81\xaf\xe6\xb3\xa1/102.jpg'
 b'data/train/\xe5\xba\x9f\xe5\xbc\x83\xe7\x81\xaf\xe6\xb3\xa1/103.jpeg'
 b'data/train/\xe5\xba\x9f\xe5\xbc\x83\xe7\x81\xaf\xe6\xb3\xa1/104.jpg'
 b'data/train/\xe5\xba\x9f\xe5\xbc\x83\xe7\x81\xaf\xe6\xb3\xa1/105.jpeg'
 b'data/train/\xe5\xba\x9f\xe5\xbc\x83\xe7\x81\xaf\xe6\xb3\xa1/106.jpeg'
 b'data/train/\xe5\xba\x9f\xe5\xbc\x83\xe7\x81\xaf\xe6\xb3\xa1/107.jpg'
 b'data/train/\xe5\xba\x9f\xe5\xbc\x83\xe7\x81\xaf\xe6\xb3\xa1/108.jpg'
 b'data/train/\xe5\xba\x9f\xe5\xbc\x83\xe7\x81\xaf\xe6\xb3\xa1/109.jpg'
 b'data/train/\xe5\xba\x9f\xe5\xbc\x83\xe7\x81\xaf\xe6\xb3\xa1/11.jpeg'
 b'data/train/\xe5\xba\x9f\xe5\xbc\

data/train/花盆
tf.Tensor(
[b'data/train/\xe8\x8a\xb1\xe7\x9b\x86/1.jpeg'
 b'data/train/\xe8\x8a\xb1\xe7\x9b\x86/100.jpg'
 b'data/train/\xe8\x8a\xb1\xe7\x9b\x86/101.jpg'
 b'data/train/\xe8\x8a\xb1\xe7\x9b\x86/102.jpg'
 b'data/train/\xe8\x8a\xb1\xe7\x9b\x86/103.jpg'
 b'data/train/\xe8\x8a\xb1\xe7\x9b\x86/104.jpg'
 b'data/train/\xe8\x8a\xb1\xe7\x9b\x86/105.jpg'
 b'data/train/\xe8\x8a\xb1\xe7\x9b\x86/106.jpg'
 b'data/train/\xe8\x8a\xb1\xe7\x9b\x86/107.jpg'
 b'data/train/\xe8\x8a\xb1\xe7\x9b\x86/108.png'
 b'data/train/\xe8\x8a\xb1\xe7\x9b\x86/109.jpg'
 b'data/train/\xe8\x8a\xb1\xe7\x9b\x86/11.jpg'
 b'data/train/\xe8\x8a\xb1\xe7\x9b\x86/110.jpeg'
 b'data/train/\xe8\x8a\xb1\xe7\x9b\x86/111.jpg'
 b'data/train/\xe8\x8a\xb1\xe7\x9b\x86/112.jpg'
 b'data/train/\xe8\x8a\xb1\xe7\x9b\x86/113.jpg'
 b'data/train/\xe8\x8a\xb1\xe7\x9b\x86/114.jpg'
 b'data/train/\xe8\x8a\xb1\xe7\x9b\x86/115.jpg'
 b'data/train/\xe8\x8a\xb1\xe7\x9b\x86/116.jpg'
 b'data/train/\xe8\x8a\xb1\xe7\x9b\x86/117.jpg'
 b'data/train/\x

data/train/卫生纸
tf.Tensor(
[b'data/train/\xe5\x8d\xab\xe7\x94\x9f\xe7\xba\xb8/1.jpeg'
 b'data/train/\xe5\x8d\xab\xe7\x94\x9f\xe7\xba\xb8/10.jpg'
 b'data/train/\xe5\x8d\xab\xe7\x94\x9f\xe7\xba\xb8/100.jpg'
 b'data/train/\xe5\x8d\xab\xe7\x94\x9f\xe7\xba\xb8/101.jpg'
 b'data/train/\xe5\x8d\xab\xe7\x94\x9f\xe7\xba\xb8/102.jpg'
 b'data/train/\xe5\x8d\xab\xe7\x94\x9f\xe7\xba\xb8/103.jpg'
 b'data/train/\xe5\x8d\xab\xe7\x94\x9f\xe7\xba\xb8/104.jpg'
 b'data/train/\xe5\x8d\xab\xe7\x94\x9f\xe7\xba\xb8/105.jpg'
 b'data/train/\xe5\x8d\xab\xe7\x94\x9f\xe7\xba\xb8/106.jpg'
 b'data/train/\xe5\x8d\xab\xe7\x94\x9f\xe7\xba\xb8/107.jpg'
 b'data/train/\xe5\x8d\xab\xe7\x94\x9f\xe7\xba\xb8/108.jpg'
 b'data/train/\xe5\x8d\xab\xe7\x94\x9f\xe7\xba\xb8/109.jpg'
 b'data/train/\xe5\x8d\xab\xe7\x94\x9f\xe7\xba\xb8/11.png'
 b'data/train/\xe5\x8d\xab\xe7\x94\x9f\xe7\xba\xb8/110.jpg'
 b'data/train/\xe5\x8d\xab\xe7\x94\x9f\xe7\xba\xb8/111.jpg'
 b'data/train/\xe5\x8d\xab\xe7\x94\x9f\xe7\xba\xb8/112.jpg'
 b'data/train/\xe

data/train/纱布
tf.Tensor(
[b'data/train/\xe7\xba\xb1\xe5\xb8\x83/1.jpg'
 b'data/train/\xe7\xba\xb1\xe5\xb8\x83/10.jpg'
 b'data/train/\xe7\xba\xb1\xe5\xb8\x83/100.jpg'
 b'data/train/\xe7\xba\xb1\xe5\xb8\x83/101.jpg'
 b'data/train/\xe7\xba\xb1\xe5\xb8\x83/102.jpg'
 b'data/train/\xe7\xba\xb1\xe5\xb8\x83/103.jpg'
 b'data/train/\xe7\xba\xb1\xe5\xb8\x83/104.jpg'
 b'data/train/\xe7\xba\xb1\xe5\xb8\x83/105.jpg'
 b'data/train/\xe7\xba\xb1\xe5\xb8\x83/106.jpg'
 b'data/train/\xe7\xba\xb1\xe5\xb8\x83/107.jpg'
 b'data/train/\xe7\xba\xb1\xe5\xb8\x83/108.jpg'
 b'data/train/\xe7\xba\xb1\xe5\xb8\x83/109.jpg'
 b'data/train/\xe7\xba\xb1\xe5\xb8\x83/11.jpg'
 b'data/train/\xe7\xba\xb1\xe5\xb8\x83/110.jpg'
 b'data/train/\xe7\xba\xb1\xe5\xb8\x83/111.jpg'
 b'data/train/\xe7\xba\xb1\xe5\xb8\x83/112.jpg'
 b'data/train/\xe7\xba\xb1\xe5\xb8\x83/113.jpg'
 b'data/train/\xe7\xba\xb1\xe5\xb8\x83/114.jpg'
 b'data/train/\xe7\xba\xb1\xe5\xb8\x83/115.jpg'
 b'data/train/\xe7\xba\xb1\xe5\xb8\x83/116.jpg'
 b'data/train/\xe7\

data/train/棉签
tf.Tensor(
[b'data/train/\xe6\xa3\x89\xe7\xad\xbe/1.jpg'
 b'data/train/\xe6\xa3\x89\xe7\xad\xbe/10.jpg'
 b'data/train/\xe6\xa3\x89\xe7\xad\xbe/100.jpg'
 b'data/train/\xe6\xa3\x89\xe7\xad\xbe/101.jpg'
 b'data/train/\xe6\xa3\x89\xe7\xad\xbe/102.jpg'
 b'data/train/\xe6\xa3\x89\xe7\xad\xbe/103.jpg'
 b'data/train/\xe6\xa3\x89\xe7\xad\xbe/104.jpg'
 b'data/train/\xe6\xa3\x89\xe7\xad\xbe/105.jpg'
 b'data/train/\xe6\xa3\x89\xe7\xad\xbe/106.jpg'
 b'data/train/\xe6\xa3\x89\xe7\xad\xbe/107.jpg'
 b'data/train/\xe6\xa3\x89\xe7\xad\xbe/108.jpg'
 b'data/train/\xe6\xa3\x89\xe7\xad\xbe/109.jpg'
 b'data/train/\xe6\xa3\x89\xe7\xad\xbe/11.jpg'
 b'data/train/\xe6\xa3\x89\xe7\xad\xbe/110.jpg'
 b'data/train/\xe6\xa3\x89\xe7\xad\xbe/111.jpeg'
 b'data/train/\xe6\xa3\x89\xe7\xad\xbe/112.jpg'
 b'data/train/\xe6\xa3\x89\xe7\xad\xbe/113.jpg'
 b'data/train/\xe6\xa3\x89\xe7\xad\xbe/114.jpg'
 b'data/train/\xe6\xa3\x89\xe7\xad\xbe/115.jpg'
 b'data/train/\xe6\xa3\x89\xe7\xad\xbe/116.jpg'
 b'data/train/\xe6

data/train/橡胶手套
tf.Tensor(
[b'data/train/\xe6\xa9\xa1\xe8\x83\xb6\xe6\x89\x8b\xe5\xa5\x97/1.jpg'
 b'data/train/\xe6\xa9\xa1\xe8\x83\xb6\xe6\x89\x8b\xe5\xa5\x97/10.jpg'
 b'data/train/\xe6\xa9\xa1\xe8\x83\xb6\xe6\x89\x8b\xe5\xa5\x97/100.jpg'
 b'data/train/\xe6\xa9\xa1\xe8\x83\xb6\xe6\x89\x8b\xe5\xa5\x97/101.jpg'
 b'data/train/\xe6\xa9\xa1\xe8\x83\xb6\xe6\x89\x8b\xe5\xa5\x97/102.jpg'
 b'data/train/\xe6\xa9\xa1\xe8\x83\xb6\xe6\x89\x8b\xe5\xa5\x97/103.jpg'
 b'data/train/\xe6\xa9\xa1\xe8\x83\xb6\xe6\x89\x8b\xe5\xa5\x97/104.jpg'
 b'data/train/\xe6\xa9\xa1\xe8\x83\xb6\xe6\x89\x8b\xe5\xa5\x97/105.jpg'
 b'data/train/\xe6\xa9\xa1\xe8\x83\xb6\xe6\x89\x8b\xe5\xa5\x97/106.jpg'
 b'data/train/\xe6\xa9\xa1\xe8\x83\xb6\xe6\x89\x8b\xe5\xa5\x97/107.jpg'
 b'data/train/\xe6\xa9\xa1\xe8\x83\xb6\xe6\x89\x8b\xe5\xa5\x97/108.jpg'
 b'data/train/\xe6\xa9\xa1\xe8\x83\xb6\xe6\x89\x8b\xe5\xa5\x97/109.jpg'
 b'data/train/\xe6\xa9\xa1\xe8\x83\xb6\xe6\x89\x8b\xe5\xa5\x97/11.jpg'
 b'data/train/\xe6\xa9\xa1\xe8\x83\xb6\xe

data/train/化妆刷
tf.Tensor(
[b'data/train/\xe5\x8c\x96\xe5\xa6\x86\xe5\x88\xb7/1.jpeg'
 b'data/train/\xe5\x8c\x96\xe5\xa6\x86\xe5\x88\xb7/10.jpg'
 b'data/train/\xe5\x8c\x96\xe5\xa6\x86\xe5\x88\xb7/100.jpg'
 b'data/train/\xe5\x8c\x96\xe5\xa6\x86\xe5\x88\xb7/101.jpg'
 b'data/train/\xe5\x8c\x96\xe5\xa6\x86\xe5\x88\xb7/102.jpg'
 b'data/train/\xe5\x8c\x96\xe5\xa6\x86\xe5\x88\xb7/103.jpg'
 b'data/train/\xe5\x8c\x96\xe5\xa6\x86\xe5\x88\xb7/104.jpg'
 b'data/train/\xe5\x8c\x96\xe5\xa6\x86\xe5\x88\xb7/105.jpg'
 b'data/train/\xe5\x8c\x96\xe5\xa6\x86\xe5\x88\xb7/106.jpg'
 b'data/train/\xe5\x8c\x96\xe5\xa6\x86\xe5\x88\xb7/107.jpeg'
 b'data/train/\xe5\x8c\x96\xe5\xa6\x86\xe5\x88\xb7/108.jpg'
 b'data/train/\xe5\x8c\x96\xe5\xa6\x86\xe5\x88\xb7/109.jpg'
 b'data/train/\xe5\x8c\x96\xe5\xa6\x86\xe5\x88\xb7/11.jpg'
 b'data/train/\xe5\x8c\x96\xe5\xa6\x86\xe5\x88\xb7/110.jpg'
 b'data/train/\xe5\x8c\x96\xe5\xa6\x86\xe5\x88\xb7/111.jpg'
 b'data/train/\xe5\x8c\x96\xe5\xa6\x86\xe5\x88\xb7/112.jpeg'
 b'data/train/\

data/train/创口贴
tf.Tensor(
[b'data/train/\xe5\x88\x9b\xe5\x8f\xa3\xe8\xb4\xb4/1.jpg'
 b'data/train/\xe5\x88\x9b\xe5\x8f\xa3\xe8\xb4\xb4/10.jpg'
 b'data/train/\xe5\x88\x9b\xe5\x8f\xa3\xe8\xb4\xb4/100.jpg'
 b'data/train/\xe5\x88\x9b\xe5\x8f\xa3\xe8\xb4\xb4/101.jpg'
 b'data/train/\xe5\x88\x9b\xe5\x8f\xa3\xe8\xb4\xb4/102.jpg'
 b'data/train/\xe5\x88\x9b\xe5\x8f\xa3\xe8\xb4\xb4/103.jpg'
 b'data/train/\xe5\x88\x9b\xe5\x8f\xa3\xe8\xb4\xb4/104.jpg'
 b'data/train/\xe5\x88\x9b\xe5\x8f\xa3\xe8\xb4\xb4/105.jpg'
 b'data/train/\xe5\x88\x9b\xe5\x8f\xa3\xe8\xb4\xb4/106.jpg'
 b'data/train/\xe5\x88\x9b\xe5\x8f\xa3\xe8\xb4\xb4/107.jpg'
 b'data/train/\xe5\x88\x9b\xe5\x8f\xa3\xe8\xb4\xb4/108.jpg'
 b'data/train/\xe5\x88\x9b\xe5\x8f\xa3\xe8\xb4\xb4/109.jpg'
 b'data/train/\xe5\x88\x9b\xe5\x8f\xa3\xe8\xb4\xb4/11.jpg'
 b'data/train/\xe5\x88\x9b\xe5\x8f\xa3\xe8\xb4\xb4/110.jpg'
 b'data/train/\xe5\x88\x9b\xe5\x8f\xa3\xe8\xb4\xb4/111.jpg'
 b'data/train/\xe5\x88\x9b\xe5\x8f\xa3\xe8\xb4\xb4/112.jpg'
 b'data/train/\xe5

data/train/一次性筷子
tf.Tensor(
[b'data/train/\xe4\xb8\x80\xe6\xac\xa1\xe6\x80\xa7\xe7\xad\xb7\xe5\xad\x90/1.jpg'
 b'data/train/\xe4\xb8\x80\xe6\xac\xa1\xe6\x80\xa7\xe7\xad\xb7\xe5\xad\x90/10.jpg'
 b'data/train/\xe4\xb8\x80\xe6\xac\xa1\xe6\x80\xa7\xe7\xad\xb7\xe5\xad\x90/100.jpg'
 b'data/train/\xe4\xb8\x80\xe6\xac\xa1\xe6\x80\xa7\xe7\xad\xb7\xe5\xad\x90/101.jpg'
 b'data/train/\xe4\xb8\x80\xe6\xac\xa1\xe6\x80\xa7\xe7\xad\xb7\xe5\xad\x90/102.jpg'
 b'data/train/\xe4\xb8\x80\xe6\xac\xa1\xe6\x80\xa7\xe7\xad\xb7\xe5\xad\x90/103.jpg'
 b'data/train/\xe4\xb8\x80\xe6\xac\xa1\xe6\x80\xa7\xe7\xad\xb7\xe5\xad\x90/105.jpg'
 b'data/train/\xe4\xb8\x80\xe6\xac\xa1\xe6\x80\xa7\xe7\xad\xb7\xe5\xad\x90/107.png'
 b'data/train/\xe4\xb8\x80\xe6\xac\xa1\xe6\x80\xa7\xe7\xad\xb7\xe5\xad\x90/108.jpg'
 b'data/train/\xe4\xb8\x80\xe6\xac\xa1\xe6\x80\xa7\xe7\xad\xb7\xe5\xad\x90/109.jpg'
 b'data/train/\xe4\xb8\x80\xe6\xac\xa1\xe6\x80\xa7\xe7\xad\xb7\xe5\xad\x90/11.jpg'
 b'data/train/\xe4\xb8\x80\xe6\xac\xa1\xe6\x80\xa7\x

In [ ]:
image_raw_data = tf.io.read_file('./data/train/打火机/117.png')
image_decode = tf.image.decode_png(image_raw_data)

In [ ]:
image_decode